In [ ]:
import numpy as np
import pandas as pd


**Question 1**

In [ ]:
# Given a NumPy array , arr=np.array( [ [6,9,12] , [8,3,7] , [9,8,0] ] ) Find the correct command from the following options to get an output array as [27 18 17]?

In [ ]:
arr=np.array( [ [6,9,12] , [8,3,7] , [9,8,0] ] )
print(arr)
np.sum(arr, axis=1)

[[ 6  9 12]
 [ 8  3  7]
 [ 9  8  0]]


array([27, 18, 17])

**Question 2**

In [ ]:
# Consider a variable job=”analyst”.Which of the following expression(s) will retrieve the last from the string?

In [ ]:
job_name = "analyst"
list_1 = list(job_name)
print(list_1)
arr_1 = np.array(list_1)
print(arr_1[::-1][0])
print(arr_1[-1])

['a', 'n', 'a', 'l', 'y', 's', 't']
t
t


**Question 3**

In [ ]:
# Create a sequence number from 13 to 22 and increment by 4 .What is the index element 17?

In [ ]:
num_array = np.arange(13,22,4)

# num_array = np.array([17,17,18,17])
print(num_array== 17)
print(np.where(num_array== 17)[0])
print(np.where(num_array== 17))
print(np.where(num_array== 17)[0][0])

[False  True False]
[1]
(array([1]),)
1


In [ ]:
list_1 =[3,9,12,15]
a=(x**3 for x in list_1)
print(next(a))

27


**Question 5**

In [ ]:
# The command to find the number of elements in the following array
N=np.array([ 99 , 'None' , 49 , 'Nan', 'str' , np.nan ,63 , 50 ,'( )' ,'[ ]' ,'{ }'])
print(np.size(N))
print(len(N))

11
11


**Question 6**

In [ ]:
# # A 2-dimensional array with 3 rows and 3 columns containing random numbers from 1
# to 9 is given as – arr1= np.array([[3,2,1],[6,4,5],[8,7,9]])
# Find the difference between the maximum element across the columns and the minimum
# element across the rows.

arr1= np.array([[3,2,1],[6,4,5],[8,7,9]])
print(arr1)
print(arr1[:,0:1].max()- arr1[0:1,:].min())
print(arr1[:,1:2].max()- arr1[1:2,:].min())
print(arr1[:,2:].max()- arr1[2:,:].min())




[[3 2 1]
 [6 4 5]
 [8 7 9]]
7
3
2


**Question 7**

In [ ]:
# Create a nested numpy array from a given dictionary data.
sample = {1: list([1,2]),2: list([[1],[2]]),3: list([[1,2], [3,4], [4,5]]),4: list([1]),5: list([1,2,3,4,5])}
dict_narray = np.array([[1, list([1,2])],
                        [2, list([[1],[2]])],
                        [3, list([[1,2], [3,4], [4,5]])],
                        [4, list([1])],
                        [5, list([1,2,3,4,5])]], dtype= object)
np.ndim(dict_narray)
dict_narray

array([[1, list([1, 2])],
       [2, list([[1], [2]])],
       [3, list([[1, 2], [3, 4], [4, 5]])],
       [4, list([1])],
       [5, list([1, 2, 3, 4, 5])]], dtype=object)

# **Question 8** - correlation coefficient bold text


In [ ]:
A1 = np.array([[4,12,29]])
B1 = np.array([[13,21,4]])
np.cross(A1,B1)

array([[-561,  361,  -72]])

In [ ]:
# Given two vectors A and B, find the correlation coefficient of the following vectors.

In [ ]:
A = np.array([1,3,5,7,9,11,13,15,17,19,21,23,25])
B = np.array([0,2,4,6,8,10,12,14,16,18,20, 22, 24])
np.corrcoef(A,B)

array([[1., 1.],
       [1., 1.]])

In [ ]:
A = np.array([1,2,6])
B = np.array([1,3, 8])
# C = B.reshape(1,3)
print(A)
# print(C)
# help(np.dot(A,C))
np.cross(A,B)

[1 2 6]


array([-2, -2,  1])

**Question 9** For the given arrays, array1 and array2, if we stack the two arrays row wise, what will be the output? array1 = np.array([[1,2],[3,4]]) array2 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])

Insight Concept : column_stack function on an array combines the rows of one array to another and for any stacking dimension should be same for the array.

In [ ]:
array1 = np.array([[1,2],
                    [3,4]])
array2 = np.array([[5,6],
                    [7,8]])
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
# print(array1)
# print(array2)
np.vstack((array1,array2))
# np.column_stack((array1,array2))

array([[ 1,  2],
       [ 3,  4],
       [ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
array_1 = np.column_stack((array1, array2))
print(array_1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 5

# **Question 10** -     Stacking Of Array

In [ ]:
# Given two numpy arrays, we will perform Horizontally stack the given arrays array1 and
# array2. What will be the output of the above operation? The sample arrays are as follows.
# Array1 = numpy.arange(20,2)
# Array2 = numpy.array([1,2,3,4,5,6,7,8,9,10])

# The arrange function param (<Start Index>, <End Index>, <Step interval>)

In [ ]:
Array1 = np.arange(0,20)
Array2d = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(Array1)
print(Array2d)
array_3 = [Array1, Array2d]
print(f"concatination :",array_3)
print(f"dim of concatinated array :",type(array_3))
# print(f"HSTACK :",np.hstack(array_3)
Array1d = np.array([1,2,3,4,5,6,7,8,9,10])
array_4 = np.hstack((Array1,Array1d))
print(f"HSTACK :",array_4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
concatination : [array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19]), array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])]
dim of concatinated array : <class 'list'>
HSTACK : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19  1  2  3  4
  5  6  7  8  9 10]


In [ ]:
help(np.arange)

**Question 11**

In [ ]:
# In the given array, how can we get the following output – array([2, 5, 8]). Sample = numpy.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])

In [ ]:
Sample = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9],
                    [10,11,12],
                    [13,14,15]])

Sample[0:3,1]

array([2, 5, 8])

**Question 12** - Column wise stacking

In [ ]:
import numpy as np
# For the given arrays, array1 and array2, if we stack the two arrays column wise, what will
# be the output?
array1 = np.array([[1,2],
                  [3,4]])
array2 = np.array([[5,6],
                  [7,8]])
print(f"column wise 1 :\n",np.column_stack((array1,array2)))
print("hstack 1: \n",np.hstack((array1,array2)))
array3 = np.vstack((array1,array2))
array4 = np.hstack((array1,array2))
arr_1 = np.array([1,2,3])
arr_2 = np.array([2,4,4])
print(f"column wise 2 :\n",np.column_stack((arr_1,arr_2)))
print("hstack 2: \n",np.hstack((arr_1,arr_2)))


column wise 1 :
 [[1 2 5 6]
 [3 4 7 8]]
hstack 1: 
 [[1 2 5 6]
 [3 4 7 8]]
column wise 2 :
 [[1 2]
 [2 4]
 [3 4]]
hstack 2: 
 [1 2 3 2 4 4]


# **Question** 13

In [ ]:
# A 2-dimensional array with 3 rows and 3 columns containing random numbers from 1
# to 9 is given as – arr1= np.array([[3,2,1],[6,4,5],[8,7,9]])
# Find the difference between the maximum element across the columns and the minimum
# element across the rows

In [ ]:
arr1= np.array([[3,2,1],
                [6,4,5],
                [8,7,9]])
# print(arr1[:,2:])
# print(arr1[:,:1].max())
column_max = np.array([arr1[:,:1].max(), arr1[:,1:2].max(), arr1[:,2:].max()])
row_min = np.array([arr1[:1,:].min(), arr1[1:2,:].min(), arr1[2:,:].min()])
print(column_max)
print(row_min)
difference = column_max - row_min
print(difference)

[8 7 9]
[1 4 7]
[7 3 2]


**Question** **14**

In [ ]:
List =[3,9,12,15]
for x in List :
  print(x)
a=(x**3 for x in List)
print(type(a))
print(next(a))

**Question 15**

In [ ]:
array = np.array([10,3,1,203,404,204,20,302,30,402,192])
array[::-1]

**Question 16**

In [ ]:
# How to replace all values greater than a given value with a given cutoff? For
# example: In array ‘a’, replace all values greater than 30 to 30 and less than 10 to 10.
# Input:
# np.random.seed(100)
# a = np.random.uniform(1,50, 20)

In [ ]:
import numpy as np
np.random.seed(100)
a = np.random.uniform(1,50, 20)
print(a)
# a[np.where(a > 30)]=30
# a[np.where(a < 10)]=10
print(np.where(a < 10, 10, np.where(a > 30, 30, a)))


**Question 17**

In [ ]:
# For the given arrays, array1 and array2, if we stack the two arrays row wise, what will be
# the output?
# array1 = np.array([[1,2],[3,4]])
# array2 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])

In [ ]:
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
print(np.vstack((array1,array2),dtype=object))


**Question 18**

In [ ]:
# For a given numpy array, how are you going to insert a new value at the specified position? array = np.array([10,3,1,203,404,204,20,302,30,402,192])

Elem_to_be_inserted = [1,2,3,4]

# The position to be inserted at = before 404
Insight Concept : To get the index value in numpy we have to use where function which gives a 2d array so we need to use [][] to get actual index value.

In [ ]:
array = np.array([10,3,1,203,404,204,20,302,30,402,192])
Elem_to_be_inserted = [1,2,3,4]
print(f"Array of where", array[np.where(array==404)])
print(f"Type Of Where ", type(np.where(array==404)))
print(f"Content of Where ", (np.where(array==404)))
indexValue = np.where(array==404)[0][0]
print(indexValue)
# np.index(404)

np.insert(array, indexValue, Elem_to_be_inserted)
# array.insert(np.where(array==404),Elem_to_be_inserted)
# array

**Question 19**

In [ ]:
import numpy as np
a = np.arange(360).reshape((3,4,5,6))

# help(np.reshape)
# Reshape (3,4,5,6)
# It is creating 4 dimensional array as it has 4 numbers
  # 5- Number of Rows
  # 6 - Number of Column
  # 4 - Number of 2 dim array in a 3 dim array
  # 3 - Number of 3 dim array in a 4 dim array
# a
b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3))
# It is creating 4 dimensional array as it has 4 numbers
  # 6- Number of Rows
  # 3 - Number of Column
  # 4 - Number of 2 dim array in a 3 dim array
  # 5 - Number of 3 dim array in a 4 dim array
b

# np.dot(a, b)[2,3,2,1,2,2]

**Question** : What will be output for the following code? import numpy as np a = np.array([3, 7, 32], dtype = complex) print(a)

In [ ]:
a = np.array([3, 7, 32], dtype = complex)
print(a)

**Question** : How to replace all values greater than a given value with a given cutoff? For example: In array ‘a’, replace all values greater than 30 to 30 and less than 10 to 10. Input: np.random.seed(100) a = np.random.uniform(1,50, 20)

In [ ]:
import numpy as np
np.random.seed(100) #Fix the randomness of a number
a = np.random.uniform(1,50, 20)
for i in range(0, len(a)):
  if a[i] > 30:
    a[i] = 30
  elif a[i] < 10:
    a[i] = 10
print(a)

In [ ]:
np.where(a < 10, 10, np.where(a > 30, 30, a))
a

**Question 20**

In [ ]:
# 11) For the given python code that implements bubble sort, what will be the output for the given numpy array.
def bub_sort(array):
  for i in range(0, len(array)):
    for j in range(0, len(array) - i - 1):
      if array[j] < array[j + 1]:
        temp = array[j]
        array[j] = array[j + 1]
        array[j+1] = temp
  return array

my_array = np.array([20,14,25,16,45,60,12,9])
print(bub_sort(my_array))

[60 45 25 20 16 14 12  9]


**Question 21**

In [ ]:
# What will be the shape of the sample numpy array after flattening it? Sample = numpy.array([[1,2],[3,4],[5,6],[7,8]])

In [ ]:
Sample = np.array([[[1,2],[3,4],[5,6],[7,8]],
                  [[1,2],[3,4],[5,6],[7,8]]])
print(Sample.flatten())

[1 2 3 4 5 6 7 8 1 2 3 4 5 6 7 8]


**Question 22**

In [ ]:
# Given two vectors A and B, find the correlation coefficient of the following vectors. A = numpy.array([1,3,5,7,9,11,13,15,17,19,21,23,25]) B = numpy.array([0,2,4,6,8,10,12,14,16,18,20, 22, 24])

In [ ]:
A = np.array([1,3,5,7,9,11,13,15,17,19,21,23,25])
B = np.array([0,2,4,6,8,10,12,14,16,18,20, 22, 24])

np.corrcoef(A,B)

**Question  For a given numpy array, how will you change the dimensions to 5 using the existing parameters in the numpy array. my_array = numpy.array([[[[1,3,4]]]])**

In [ ]:
import numpy as np

In [ ]:
narray = np.array([[[[1,3,4]]]])
np.array(narray, ndmin=5)


array([[[[[1, 3, 4]]]]])

In [ ]:
narray.shape

In [ ]:
narray.size

In [ ]:
narray.ndim

In [ ]:
np.array(narray, ndmin=5)

**Question** - For the given numpy arrays, Array1 and Array2, what will be the dot product for the same. Array1 = array([[1, 2, 3], [4, 5, 6]]) Array2 = array([[2, 3],[3, 2]])


Insight - For a dot product to work, shape for 2 array shoud be (2,3) & (3,1) or (3,2) & (2,4)

In [ ]:
import numpy as np

In [ ]:
Array1 = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
Array2 = np.array([[2, 3],
                  [3, 2],
                  [3, 6]])

In [ ]:
print(np.dot(Array1, Array2))

#[[1*2+2*3+3*3 1*3+2*2+3*6]
#[2*4+5*3+6*3]]

**Question** : In a given numpy array, using the slicing operations print the reverse of the array. array = np.array([10,3,1,203,404,204,20,302,30,402,192])

In [ ]:
array_1 = np.array([10,3,1,203,404,204,20,302,30,402,192])
print(array_1[1:8])  # print from index 1 to 7, so starting index included and ending-1 index included
print(array_1[1:8:2])
print(array_1[1:8:3])
print(array_1[::-1]) # Reverse complete array
print(array_1[::]) # print whole array
print(array_1[3::-1])
print(array_1[5::-1])
print(array_1[:8:-1])
print(array_1[8::-1]) #Get me the 1st 8 numbers and reverve it
print(array_1[5::-1]) #Get me the 1st 5 numbers and reverve it
print(array_1[5:3:-1]) #Get me the 1st 5 numbers and reverve it then show 1st (5-3) elements from reveresed numbers
print(array_1[8::-1]) #Get me the 1st 8 numbers and reverve it
print(array_1[8:2:-1]) #Get me the 1st 8 numbers and reverve it



**Question** : What is the output of the below code:  a = [[1, 0], [0, 1]]  b = [[4, 1], [2, 2]]  np.dot(a, b)

In [ ]:
 a = [[1, 0], [0, 1]]
 b = [[4, 1], [2, 2]]
 np.dot(a, b)

**Question** What is the output of the following code: a = np.arange(3*4*5*6).reshape((3,4,5,6)) b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3)) np.dot(a, b)[2,3,2,1,2,2]

**Question** : Create a 3x3 matrix using numpy, and all the values of the matrix must be a constant k.

In [ ]:
np.full((3,3), 'k')

**Class questions**

In [ ]:
import numpy as np
arr_1 = np.arange(3*5)
arr_1=arr_1.reshape((3,5))
print(arr_1)
print(arr_1.shape)
print(arr_1.ndim)
print(type(arr_1))
print(arr_1.tobytes())
print(arr_1.dtype)
print(arr_1.itemsize)
print(arr_1.data)
print(arr_1.size)

In [ ]:
tp_1 = (1,2,3,4)
print(tp_1)
print(type(tp_1))

arr_tp = np.array(tp_1)
print(arr_tp)
print(type(arr_tp))


lis_1 = [1,2,3,4]
print(lis_1)
print(type(lis_1))

arr_lis = np.array(lis_1)
print(arr_lis)
print(type(arr_lis))



dict_1 = {'a': 100, 'b': 200, 'c': 300}
print(type(dict_1))

arr_dict = np.array(dict_1.values())
print(arr_dict)
print(type(arr_dict))

arr_dict = np.array(dict_1.keys())
print(arr_dict)
print(type(arr_dict))


Create a 3x3 matrix, along with the following:

Create a 2x2 numpy array filled with zeros.
Create a 3x3 numpy array filled with ones
Create a 4x4 numpy array filled with any constant K.
Create a 2x2 empty array
Create a numpy array with a range of elements
Create a 3x3 numpy array with values that are spaced linearly in a specified interval

In [ ]:
print(np.full((2,2), 0))
print(np.full((3,3), 1))
print((np.full((4,4), 'k')))
print((np.full((4,4), 'k')).dtype)
print(np.empty((2,2)))
print((np.linspace(0,9,10)).reshape(2,5))

In [ ]:
# print((np.full((4,4), 'k')))
print((np.full((4,4), 'Prasanna')).dtype)

Create a 3x3 numpy array and perform the following operations:
- Indexing to get all the elements from the array
- Negative indexing to get all the elements from the array
- Slicing to get just the 3 row from the array
- Slicing to get the element at 3rd row and 2nd column
- Iterate over the multidimensional array to get all the rows from the array
- Iterate over the multidimensional array to get all the elements from the array

In [ ]:
arr_1 = np.arange(3*3).reshape(3,3)
print(arr_1)
print(f'all element: ',arr_1[::])
print(f"reverse: \n",arr_1[::-1])

print(arr_1[0:3,0:3])
print(arr_1[0:,1])

for i in arr_1:
  print(i)

for i in arr_1:
  for j in i:
    print(j


# CROSS PRODUCT Given two vectors A and B, find the cross product between the two vectors. A = numpy.array([[4],[12],[29]]) B = numpy.array([[13],[21],[4]])

In [28]:
import numpy as np
A = np.array([[40],
              [12],
              [29]])
print(A)
print(A.shape)
print(A.ndim)
C = np.ndarray(A, ndim=2)
# np.array(narray, ndmin=5)

B = np.array([13,21,4])
# np.cross(A,B)
# np.cross(A,B)

[[40]
 [12]
 [29]]
(3, 1)
2


TypeError: only integer scalar arrays can be converted to a scalar index

In [31]:
str_array = np.array(['ab','bcd','c','d'])
print(str_array)
print(str_array.dtype)

['ab' 'bcd' 'c' 'd']
<U3
