### Numpy, Pandas, Matplotlib and Seaborn

In [2]:
# List of libraries that are present in your env
!conda list

/bin/bash: line 1: conda: command not found


# Manage Libraries

In [3]:
# Installing a Library
!pip install numpy

In [ ]:
!pip install names

In [ ]:
# Specific Version
!pip install numpy==1.22.4

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.8/16.8 MB 52.1 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 1.23.5
    Uninstalling numpy-1.23.5:
      Successfully uninstalled numpy-1.23.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lida 0.0.10 requires fastapi, which is not installed.
lida 0.0.10 requires kaleido, which is not installed.
lida 0.0.10 requires python-multipart, which is not installed.
lida 0.0.10 requires uvicorn, which is not installed.
plotnine 0.12.4 requires numpy>=1.23.0, but you have numpy 1.22.4 which is incompatible.
tensorflow 2.15.0 requires numpy<2.0.0,>=1.23.5, but you have numpy 1.22.4 which is incompatible.


In [ ]:
# Most Recent Version
!pip install numpy --upgrade

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 40.5 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 1.22.4
    Uninstalling numpy-1.22.4:
      Successfully uninstalled numpy-1.22.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lida 0.0.10 requires fastapi, which is not installed.
lida 0.0.10 requires kaleido, which is not installed.
lida 0.0.10 requires python-multipart, which is not installed.
lida 0.0.10 requires uvicorn, which is not installed.


In [ ]:
!pip install pip --upgrade

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 13.0 MB/s eta 0:00:00
  Attempting uninstall: pip
    Found existing installation: pip 23.1.2
    Uninstalling pip-23.1.2:
      Successfully uninstalled pip-23.1.2


# Accessing a Library

In [6]:
import numpy as np

In [5]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

### Matrix and Array - Official
### Scalar and Vector - Assumptions
1. Scalar - Singular Value - 1, 2, 3, 111, 'Python'
1. Vector - One Dimensional DS - Either in ROWS or in COLUMNS - [1 2 3 4 5] (row Vector)
1. Matrix - Two Dimensional DS - Rows X Columns - Table Format
1. Array - Multi-dimensional DS(n) - 1, 2, 3, 4, 5

# Data Structures

### Scalar

In [7]:
a = np.array(10)
print(a)

10


In [8]:
type(a)

numpy.ndarray

### Vector

In [9]:
v = np.array([1,2,3,4,5])
print(v)

[1 2 3 4 5]


In [ ]:
type(v)

numpy.ndarray

In [ ]:
np_var = np.array([[['a', 'b', 1],
                   ['c','d', 2],
                   ['e', 'f', 3]]])
np_var

array([[['a', 'b', '1'],
        ['c', 'd', '2'],
        ['e', 'f', '3']]], dtype='<U21')

In [ ]:
type(np_var)

numpy.ndarray

In [ ]:
v.ndim # Number of dimensions in that variable

1

In [ ]:
np_var.ndim

3

### Matrix

In [10]:
m = np.matrix([[1,2,3], [4,5,6], [7,8,9]])
m

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [11]:
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
m.shape # (Rows, columns)

(3, 3)

In [ ]:
type(m)

numpy.matrix

In [13]:
np.matrix([[1,"A","B"], [4,"C",6], [7,8,9]])

matrix([['1', 'A', 'B'],
        ['4', 'C', '6'],
        ['7', '8', '9']], dtype='<U21')

In [14]:
np_mat_var = np.matrix([[1,2,3],
                       [4,5,6],
                       [7,8,9]])
np_mat_var

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
type(np_mat_var)

numpy.matrix

In [ ]:
np_mat_var.ndim

2

In [ ]:
np_mat_var.shape

(3, 3)

In [ ]:
# U - str
# I - int
# F - float

# Arrays

In [15]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [16]:
arr.ndim

1

In [17]:
arr1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr1.ndim

2

In [19]:
arr1.shape
# 3 - number of rows
# 3 - number of columns

(3, 3)

In [23]:
arr2 = np.array([[[1,2,3], [4,5,6], [7,8,9]],
                 [[1,2,3], [4,5,6], [7,8,9]]])
arr2

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [24]:
arr2.shape
# 2 - number of 2d array
# 3 - number of rows
# 3 - number of columns

(2, 3, 3)

In [21]:
arr2.ndim

3

In [30]:
arr3 = np.array([[[[1,2,3], [4,5,6], [7,8,9]],
                 [[1,2,3], [4,5,6], [7,8,9]]],

                   [[[1,2,3], [4,5,6], [7,8,9]],
                 [[1,2,3], [4,5,6], [7,8,9]]],

                 [[[1,2,3], [4,5,6], [7,8,9]],
                 [[1,2,3], [4,5,6], [7,8,9]]]
                 ])
arr3

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]],


       [[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]],


       [[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])

In [31]:
arr3.shape
# 2 - number of 3d array
# 2 - number of 2d array
# 3 - number of rows
# 3 - number of columns

(3, 2, 3, 3)

In [33]:
help(arr3.shape)

Help on tuple object:

class tuple(object)
 |  tuple(iterable=(), /)
 |  
 |  Built-in immutable sequence.
 |  
 |  If no argument is given, the constructor returns an empty tuple.
 |  If iterable is specified the tuple is initialized from iterable's items.
 |  
 |  If the argument is a tuple, the return value is the same object.
 |  
 |  Built-in subclasses:
 |      asyncgen_hooks
 |      UnraisableHookArgs
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __getnewargs__(self, /)
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |      Return hash(self).
 |  
 |  __iter__(self, /)
 |

In [27]:
arr3.ndim

4

In [ ]:
# OLAP - Cube - MDX

In [ ]:
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Creating Numpy Arrays

In [ ]:
arr = np.array([[1,2,3,4], [5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr.shape

(2, 4)

In [ ]:
a = [[1,2,3], [4,5,6]]
a

[[1, 2, 3], [4, 5, 6]]

In [ ]:
type(a)

list

In [ ]:
type(np.array(a))

numpy.ndarray

In [ ]:
type(a)

list

In [ ]:
np.zeros((3,2)) # Shape

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.zeros((3,2), dtype = "int") # Shape

array([[0, 0],
       [0, 0],
       [0, 0]])

In [ ]:
np.ones((3, 4), dtype = "int")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
np.full((3, 5), 10) # Constant

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [ ]:
np.full((3, 5), 10.5)

array([[10.5, 10.5, 10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5, 10.5, 10.5]])

In [ ]:
np.full((3, 5), 10, dtype = "float")

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [ ]:
two_dem_array = np.array([[10, 20, 30],
                         [40,50,60],
                         [70,80,90]])
two_dem_array

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
two_dem_array.ndim

2

In [ ]:
two_dem_array.shape

(3, 3)

In [ ]:
np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
np.ones((3,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
np.full((3,4),100, dtype=int)

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.eye(3) # Only the first part of the shape - Identity Matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Randomness within Arrays

In [ ]:
np.random.random((3, 2)) # Generates values between zero and one randomly

array([[0.18935851, 0.76425493],
       [0.87313483, 0.36781448],
       [0.96144313, 0.41759727]])

In [ ]:
np.random.randint(10, 100, (4, 5))

array([[89, 36, 82, 59, 93],
       [11, 96, 61, 43, 96],
       [59, 18, 32, 11, 89],
       [18, 18, 41, 87, 41]])

In [ ]:
np.random.randint(10, 100, (4, 5))

array([[65, 41, 59, 46, 94],
       [42, 53, 16, 94, 26],
       [59, 75, 42, 49, 84],
       [34, 72, 36, 47, 63]])

In [ ]:
np.random.seed(101) # Any number
np.random.randint(10, 100, (4, 5))

array([[21, 91, 80, 73, 97],
       [85, 19, 87, 50, 14],
       [73, 50, 70, 74, 15],
       [22, 50, 59, 93, 18]])

In [ ]:
np.random.seed(98) # Any number
np.random.randint(10, 100, (4, 5))

array([[52, 62, 73, 99, 75],
       [78, 81, 48, 12, 33],
       [12, 83, 83, 31, 12],
       [13, 89, 78, 16, 94]])

In [ ]:
np.random.seed(1) # Any number
np.random.randint(10, 100, (4, 5))

array([[47, 22, 82, 19, 85],
       [15, 89, 74, 26, 11],
       [86, 81, 16, 35, 60],
       [30, 28, 94, 21, 38]])