In [ ]:
import numpy as np
import pandas as pd


num_4 = np.array([1,2,3,4,5])
print(np.append(num_4, 6))

# prepend at 1st place
num_5 = np.append(10, num_4)
print(num_5)

# insert at 4th place
num_6=np.insert(num_5, 3, 30)
print(num_6)

# index of 30 in array
print(np.where(num_6 == 30)[0])




[1 2 3 4 5 6]
[10  1  2  3  4  5]
[10  1  2 30  3  4  5]
[3]


In [ ]:
num_1 = np.array([1,2,3,4,5])
num_2 = np.array([87,45,5,6,10])

print(np.sum([num_1,num_2], axis=0))

print(np.sum([num_1,num_2], axis=1))

[88 47  8 10 15]
[ 15 153]


In [ ]:
list_1 = list(x for x in range(1,11))
set_1 = set(x for x in range(1,11))
list_index = ['a','b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
num_1 = np.array(list_1)
ser_1 = pd.Series(list_1, index=list_index)
print(f"Series with list {ser_1}")


ser_2 = pd.Series([set_1])
print(f"Series with set {ser_2}")


Series with list a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
dtype: int64
Series with set 0    {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
dtype: object


In [ ]:
dict_1 = {"first name": "prasanna", "last name": "kumar", "Year": "2024"}
ser_1 = pd.Series(dict_1)
print (ser_1)
ser_2 = pd.Series([{"first name": "prasanna", "last name": "kumar"}, {"first name": "prasanna", "last name": "kumar"}, {"first name": "prasanna", "last name": "kumar"}])
print(ser_2)


first name    prasanna
last name        kumar
Year              2024
dtype: object
0    {'first name': 'prasanna', 'last name': 'kumar'}
1    {'first name': 'prasanna', 'last name': 'kumar'}
2    {'first name': 'prasanna', 'last name': 'kumar'}
dtype: object


In [ ]:
a = pd.Series(list(dict_1.keys()), index= (dict_1.values()))
a

prasanna    first name
kumar        last name
2024              Year
dtype: object

In [ ]:
list_1 = list(x for x in range(1,11))
ser_1 = pd.Series(list_1)
print(list(ser_1))
print(dict(ser_1))
print(tuple(ser_1))
print(set(ser_1))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10}
(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}


In [ ]:
x = int(input("Enter the size of list:"))
list_1 = list(n for n in range(1, x))
ser_1 = pd.Series(list_1)
print(ser_1)
print(ser_1[0:5])
print(ser_1.head(5))
print(ser_1[5:])
print(ser_1[-5:])
print(ser_1.tail(5))

ser_1 = list(n for n in range(1, x))
ser_1.insert(5,55)

ser_2 = pd.Series(ser_1,dtype=int)

print(ser_2)
ser_2.tail(1)

print(type(ser_2.tail(1)))

Enter the size of list:12
0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
dtype: int64
0    1
1    2
2    3
3    4
4    5
dtype: int64
0    1
1    2
2    3
3    4
4    5
dtype: int64
5      6
6      7
7      8
8      9
9     10
10    11
dtype: int64
6      7
7      8
8      9
9     10
10    11
dtype: int64
6      7
7      8
8      9
9     10
10    11
dtype: int64
0      1
1      2
2      3
3      4
4      5
5     55
6      6
7      7
8      8
9      9
10    10
11    11
dtype: int64
<class 'pandas.core.series.Series'>


In [ ]:
series_a = pd.Series([1,2,3,4,5])
series_b = pd.Series([6,7,8,9,10])

print(series_a.append(series_b, ignore_index=True) )

pd.concat([series_a, series_b], ignore_index=True)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64


<ipython-input-66-48ad31b7e960>:4: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  print(series_a.append(series_b, ignore_index=True) )


0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [ ]:
for x for x in  series_a

In [ ]:
df = pd.DataFrame([{"Name": "Prasanna Kumar", "Age": "35"}, {"Name": "Prianshu Kumar", "Age": "30"}, {"Name": "Anand Kumar", "Age": "33"}])
print(df)
for x in df.loc[:, "Age"] :
  print(x)
  if x == "30":
    print("matched the age")
    print(df.loc[df['Age'] == 30])
  else :
    continue

             Name Age
0  Prasanna Kumar  35
1  Prianshu Kumar  30
2     Anand Kumar  33
35
30
matched the age
Empty DataFrame
Columns: [Name, Age]
Index: []
33


# **  Creating Series from Different DS**

In [ ]:
import numpy as np
import pandas as pd

# Using the array
array_1 = np.array([1,2,3,4,5])
ser_array = pd.Series(array_1)
ser_array
print(f"Series using array:\n",ser_array)

# Using the list
list_1 = [1,2,3,4,5]
ser_list = pd.Series(list_1)
ser_list
print(f"Series using list:\n",ser_list)


# Using the tuple
tuple_1 = (1,2,3,4,5)
ser_tuple = pd.Series(tuple_1)
ser_tuple
print(f"Series using tuple:\n",ser_tuple)


# Using the set - Set can not be converted into the Series as SET is a Unordered Data Stucture
set_1 = {1,2,3,4,5}
#
# ser_set = pd.Series(list(set_1))
ser_set = pd.Series(np.array((set_1)))
ser_set
print(f"Series using tuple:\n",ser_set)




Series using array:
 0    1
1    2
2    3
3    4
4    5
dtype: int64
Series using list:
 0    1
1    2
2    3
3    4
4    5
dtype: int64
Series using tuple:
 0    1
1    2
2    3
3    4
4    5
dtype: int64
Series using tuple:
 0    {1, 2, 3, 4, 5}
dtype: object
